services:
  controller:
    image: ngrinder/controller
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller

  agent:
    image: ngrinder/agent
    restart: always
    links:
      - controller

  lb:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "8949:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  api:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    expose:
      - "80"
    ports:
      - "7942:80"
    environment:
      - VIRTUAL_HOST=172.17.0.1,localhost,127.0.0.1,172.18.0.4
      - VIRTUAL_PORT=80
    volumes:
      - ./main.py:/code/main.py

